### PR TITLE
Fix framework resolution when resolving dependencies

### LINKED ISSUE #725: KeyNotFoundException with 2.8.0
After updating to 2.8.0, I can not use CycloneDX anymore... This has not happened with 2.7.0.
```
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Text.Json.JsonElement.GetProperty(String propertyName)
   at CycloneDX.Services.ProjectAssetsFileService.SetIsDevDependency(String packageName, String targetRuntime, JsonElement jsonContent) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Services/ProjectAssetsFileService.cs:line 113
   at CycloneDX.Services.ProjectAssetsFileService.GetNugetPackages(String projectFilePath, String projectAssetsFilePath, Boolean isTestProject, Boolean excludeDev) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Services/ProjectAssetsFileService.cs:line 63
   at CycloneDX.Services.ProjectFileService.GetProjectNugetPackagesAsync(String projectFilePath, String baseIntermediateOutputPath, Boolean excludeTestProjects, Boolean excludeDev, String framework, String runtime) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Services/ProjectFileService.cs:line 145
   at CycloneDX.Program.OnExecuteAsync(CommandLineApplication app) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Program.cs:line 255
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
   at CycloneDX.Program.Main(String[] args) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Program.cs:line 140
   at CycloneDX.Program.<Main>(String[] args)
```

### PR DESCRIPTION
**Pull request by Falco20019**
Fixes #725 

I also adjusted the tests to reflect the possibility of having runtimes being set to avoid regression in the future.

### CODE REVIEW

File: CycloneDX/Services/ProjectAssetsFileService.cs [hunk 1]
```diff
@@ -60,15 +61,16 @@ public HashSet<NugetPackage> GetNugetPackages(string projectFilePath, string pro
...
                     {
+                        var targetAlias = TargetFrameworkToAlias(targetRuntime.TargetFramework);
                         var package = new NugetPackage
                         {
                             Name = library.Name,
                             Version = library.Version.ToNormalizedString(),
                             Scope = Component.ComponentScope.Required,
                             Dependencies = new Dictionary<string, string>(),
                             // get value from project.assets.json file ( x."project"."frameworks".<framework>."dependencies".<library.Name>."suppressParent") 
-                            IsDevDependency = SetIsDevDependency(library.Name, targetRuntime.Name, frameworksProperties),
```
Comment (Falco20019) [inline CycloneDX/Services/ProjectAssetsFileService.cs:70]: `targetRuntime.TargetFramework` is adding the runtime identifier, which is not expected.

**Comment by BlythMeister** [comment]
LGTM :)

**Review by NextFreeUsername — CHANGES_REQUESTED** [review]
The major change made here is moving the TargetFrameworkToAlias to a higher place to only run once instead of twice in each "SetIsXxx"-method, but that code actually does work.
The problem lies within the project.assets.json not having a "dependencies"-element beneath project > frameworks > "someframework".
I believe the change therefore should be to also use TryGetProperty here or test for its existence in another way.

**Comment by Falco20019** [comment]
No, the main change was to not use .Name which would include the RuntimeIdentifier. So TryParse alone would not fix it. I only additionally moved it out to avoid code duplication and improve performance. If that's not wanted, I can also adjust the PR to have it as minimal as possible.

File: CycloneDX/Services/ProjectAssetsFileService.cs (hunk 1 above)
Comment (Falco20019) [reply CycloneDX/Services/ProjectAssetsFileService.cs:70]: @NextFreeUsername This is the main change. `targetRuntime.TargetFramework.ToString()` instead of `targetRuntime.Name`. The name is internally constructed by combining the `TargetFramework` with `RuntimeIdentifier`.

**Comment by NextFreeUsername** [comment]
Of course avoiding code duplication and performance improvement is always a good idea, no comments there.
But I don't think this alone fixes the issue? Resolving the framework starting from "targets" isn't the problem in my case, it is the lack of "dependencies" beneath "frameworks".

image

**Comment by Falco20019** [comment]
Ok, in your case it's another issue then that didn't appear in my scenario :) But I will gladly adjust the PR on Monday with tests and a fix for that case if not done by any of the authors until then. Thanks for clarification, I thought you misread the change since it wasn't too obvious due to the refactoring being in the same commit.

**Comment by andreycha** [comment]
The fix doesn't cover following use case:

```json
{
  "version": 3,
  "targets": {
    ".NETFramework,Version=v4.8": {
    }
  },
  "libraries": {
  },
  "projectFileDependencyGroups": {
    ".NETFramework,Version=v4.8": [
    ]
  },
  "packageFolders": {
  },
  "project": {
    "version": "0.0.0.1",
    "restore": {
    },
    "frameworks": {
      "net48": {
      }
    },
    "runtimes": {
    }
  }
}
```

**Comment by Falco20019** [comment]
> 

It would be better to use an existing implementation like https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Frameworks/NuGetFramework.cs but this is nothing that I will fix with my PR since it's out of scope. Please create a separate issue (I'm not a maintainer here).

File: CycloneDX/Services/ProjectAssetsFileService.cs [hunk 2]
```diff
@@ -60,15 +61,16 @@ public HashSet<NugetPackage> GetNugetPackages(string projectFilePath, string pro
                     var runtimePackages = new HashSet<NugetPackage>();
                     foreach (var library in targetRuntime.Libraries.Where(lib => lib.Type != "project"))
                     {
+                        var targetAlias = TargetFrameworkToAlias(targetRuntime.TargetFramework);
```
[the remark this answers is not in the document]
Comment (Falco20019) [reply CycloneDX/Services/ProjectAssetsFileService.cs]: Addressed in the new commit.

**Review by NextFreeUsername — APPROVED** [review]

**Comment by Falco20019** [comment]
> The fix doesn't cover following use case:
> 
> ```json
> {
>   "version": 3,
>   "targets": {
>     ".NETFramework,Version=v4.8": {
>     }
>   },
>   "libraries": {
>   },
>   "projectFileDependencyGroups": {
>     ".NETFramework,Version=v4.8": [
>     ]
>   },
>   "packageFolders": {
>   },
>   "project": {
>     "version": "0.0.0.1",
>     "restore": {
>     },
>     "frameworks": {
>       "net48": {
>       }
>     },
>     "runtimes": {
>     }
>   }
> }
> ```

I gave it another look, since it just felt badly implemented with all the code duplication and manual parsing of the JSON while the LockFile is used for other things. I therefore reimplemented the feature and removed some code added in 2.8.0 not necessary anymore. By this change, `net48` should also be supported now.

File: CycloneDX/Program.cs [hunk 3]
```diff
@@ -128,9 +127,8 @@ class Program {
 #endregion options
 
         internal static IFileSystem fileSystem = new FileSystem();
-        internal static readonly IJsonDocs jsonDoc = new JsonDocs();
         internal static readonly IDotnetCommandService dotnetCommandService = new DotnetCommandService();
-        internal static readonly IProjectAssetsFileService projectAssetsFileService = new ProjectAssetsFileService(fileSystem, dotnetCommandService, () => new AssetFileReader(), jsonDoc);
```
Comment (Falco20019) [inline CycloneDX/Program.cs:133]: This is reverted to the 2.7.0 state, as this change is not needed by my approach.

File: CycloneDX/Services/ProjectAssetsFileService.cs [hunk 4]
```diff
@@ -48,27 +47,25 @@ public HashSet<NugetPackage> GetNugetPackages(string projectFilePath, string pro
             if (_fileSystem.File.Exists(projectAssetsFilePath))
             {
                 var assetFileReader = _assetFileReaderFactory();
-                string jsonContent = assetFileReader.ReadAllText(projectAssetsFilePath);
-                JsonDocument assetFileObject = _assetJsonObject.Parse(jsonContent);
-                // get all direct nuget dependencies of the project
-                JsonElement frameworksProperties = assetFileObject.RootElement.GetProperty("project").GetProperty("frameworks");
-
                 var assetsFile = assetFileReader.Read(projectAssetsFilePath);
```
Comment (Falco20019) [inline CycloneDX/Services/ProjectAssetsFileService.cs:50]: Since the `assetFile` is already parsed as `LockFile` from the data hat `assetJsonObject` would usually be, I replaced this by getting the framework dependencies from the lock file.

File: CycloneDX/Services/ProjectAssetsFileService.cs [hunk 5]
```diff
@@ -48,27 +47,25 @@ public HashSet<NugetPackage> GetNugetPackages(string projectFilePath, string pro
...
 
                 foreach (var targetRuntime in assetsFile.Targets)
                 {
                     var runtimePackages = new HashSet<NugetPackage>();
+                    var targetFramework = assetsFile.PackageSpec.GetTargetFramework(targetRuntime.TargetFramework);
```
Comment (Falco20019) [inline CycloneDX/Services/ProjectAssetsFileService.cs:55]: Before the PR, `targetRuntime.Name` was used to resolve the framework. This sadly includes the `RuntimeIdentifier` which is not part of the package spec and would lead to exceptions (my initial report).

The `LockFile` already has support for resolving this without the need of manually trying to map this, making `TargetFrameworkToAlias` obsolete.

File: CycloneDX/Services/ProjectAssetsFileService.cs [hunk 6]
```diff
@@ -48,27 +47,25 @@ public HashSet<NugetPackage> GetNugetPackages(string projectFilePath, string pro
...
+                    var dependencies = targetFramework.Dependencies;
+
                     foreach (var library in targetRuntime.Libraries.Where(lib => lib.Type != "project"))
                     {
+                        var libs = dependencies.FirstOrDefault(ld => ld.Name.Equals(library.Name));
```
Comment (Falco20019) [inline CycloneDX/Services/ProjectAssetsFileService.cs:60]: `FirstOrDefault` will return `null` if the library is not part of the `dependencies` section.

File: CycloneDX/Services/ProjectAssetsFileService.cs [hunk 7]
```diff
@@ -95,51 +92,13 @@ public HashSet<NugetPackage> GetNugetPackages(string projectFilePath, string pro
...
         {
-            string framework = TargetFrameworkToAlias(targetRuntime);
-            JsonElement packageProperties;
-            if (jsonContent.GetProperty(framework).GetProperty("dependencies").TryGetProperty(packageName, out packageProperties))
-            {
-                // every direct reference has target property
-                return packageProperties.TryGetProperty("target", out _);
-            }
-            return false;
+            return dependency?.ReferenceType == LibraryDependencyReferenceType.Direct;
```
Comment (Falco20019) [inline CycloneDX/Services/ProjectAssetsFileService.cs:97]: I made sure by checking the implementation that this is indeed how the target is mapped to. It also has the benefit that it is already mapped onto exactly what we expect (and catches some other side-cases not caught by the existing code).

File: CycloneDX/Services/ProjectAssetsFileService.cs [hunk 8]
```diff
@@ -95,51 +92,13 @@ public HashSet<NugetPackage> GetNugetPackages(string projectFilePath, string pro
...
-                target = target.ToLowerInvariant().TrimStart('.');
-                var targetParts = target.Split(",version=v");
-                if (targetParts.Length == 2)
-                {
-                    return string.Join("", targetParts);
-                }
-                return targetParts[0];
-            }
-            return null;
+            return dependency != null && dependency.SuppressParent != LibraryIncludeFlagUtils.DefaultSuppressParent;
```
Comment (Falco20019) [inline CycloneDX/Services/ProjectAssetsFileService.cs:101]: The existance of `suppressParent` is not a good metric for checking if it's a development dependency, as it CAN be set in other occasions as well. The existing code would have failed if `PrivateAssets="Build;Analyzers"` was set on the `PackageReference` (keeping `ContentFiles`).

File: CycloneDX/Services/ProjectAssetsFileService.cs [hunk 9]
```diff
@@ -95,51 +92,13 @@ public HashSet<NugetPackage> GetNugetPackages(string projectFilePath, string pro
...
-        /// <summary>
-        /// Converts an asset file's target framework value into a csproj target framework value.
-        ///
-        /// Examples:
-        ///     .NetStandard,Version=V3.1 => netstandard3.1
-        ///     .NetCoreApp,Version=V3.1  => netcoreapp3.1
-        ///     netcoreapp3.1  => netcoreapp3.1
-        ///     net6.0  => net6.0
-        /// </summary>
-        private string TargetFrameworkToAlias(string target)
```
Comment (Falco20019) [inline CycloneDX/Services/ProjectAssetsFileService.cs:130]: As @NextFreeUsername mentioned, this lacks support for .NET Framework (and others).

**Review by Falco20019 — COMMENTED** [review]
Some write-up about the intentions behind the changes I made.

File: CycloneDX/Services/ProjectAssetsFileService.cs (hunk 8 above)
Comment (Falco20019) [reply CycloneDX/Services/ProjectAssetsFileService.cs:101]: Technically, the ones interesting here would be `Compile`, `Runtime` and `Native`. If any of these would NOT be suppressed, at least some files from the package WOULD end up in the deployable. `DefaultSuppressParent` contains  `Build;ContentFiles;Analyzers` are marked private assets (see https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets and https://github.com/NuGet/NuGet.Client/blob/6.7.0.110/src/NuGet.Core/NuGet.LibraryModel/LibraryIncludeFlagUtils.cs#L16-L20 for reference).

**Review by NextFreeUsername — APPROVED** [review]
Very neat found I must say to use those NuGet-libraries instead of own logic.
This code looks a lot better than it used to.
Thanks a lot!

**Comment by BlythMeister** [comment]
@coderpatros LGTM?

**Comment by Falco20019** [comment]
@coderpatros Could you please have a look? The release is sadly broken like this and we had to blacklist the version in our Artifactory to avoid users getting it and breaking our environment.

**Review by coderpatros — APPROVED** [review]

**Comment by jonasaebersold** [comment]
Nice! We had the same issue and the new release (2.8.1) fixed it. Thank you all for fixing and reviewing the issue.

**Comment by NextFreeUsername** [comment]
Thanks a lot @Falco20019! Works like a charm on the new 2.8.1.
